#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jan 13 10:37:11 2021

Class to read GMI simulations generated by ARTS
Can read in either one file or a list of files

@author: inderpreet
"""


import scipy.io
import numpy as np
import matplotlib.pyplot as plt



class GMI():
      
    
    def __init__(self, filenames):
        """
        Class to read GMi simulations generated by ARTS
        ----------
        filenames : string/list of strings containing the filename(s)

        Returns
        -------
        None.

        """
        
        if np.isscalar(filenames):
#            print ('doing only one file')
            filenames = [filenames]
        self.mat = []
        for file in filenames:
            self.mat.append(scipy.io.loadmat(file))
            
        
    def get_data(self, parameter):    
        """
        method to read in the data from *.mat file   
    
            Parameters
        ----------
        parameter : string containing name of the parameter to be extracted

        Returns
        -------
        data : np.array of requested data

        """
        
        if parameter not in ["Tb", "iwp", "lat", "lon", "pos" ,
                              "stype", "z0", "p0", "t0", "rwp", "wvp"]:
            raise ValueError("parameter should be one of [Tb, iwp, lat, lon, pos, stype, z0, p0, t0, rwp, wvp]")
            
        data = []    
        if parameter == "Tb":
            for i in range(len(self.mat)):
                mat = self.mat[i]
                data.append(mat["Tb"])
            return data
        else:
            for i in range(len(self.mat)):
                mat = self.mat[i]
                data.append(mat["B"][parameter][0,0])
            return data
        
        
    def get_O(self, parameter):
        """
        method to read in ARTS setup inputs

        Parameters
        ----------
        parameter : string containing the name of the input to be extracted

        Raises
        ------
            valueError if the parameter is not in the list 
            
        Returns
        -------
        data : list of arrays containing the parameter desired

        """
        
        if parameter not in ["icehabit", "icepsd", "icesize", "rainpsd", "lsampling" ,
                              "pratio_csat", "pratio_gmi", "phase_tlim"]:
            raise (ValueError("parameter should be one of [icehabit, icepsd, icesize, rainpsd, lsampling, pratio_csat, pratio_gmi, phase_tlim]"),)
        data = []
        for i in range(len(self.mat)):
                mat = self.mat[i]
                data.append(mat["O"][parameter][0,0])
        return data                      
         
        

    
    @property
    def tb(self):
        """
        brightness temperatures

        Returns
        -------
        np.array of TB values

        """
        tb = self.get_data('Tb')
        tb = np.concatenate(tb, axis = 0)
        return np.squeeze(tb)
    
    @property
    def iwp(self):
        """
        ice water path

        Returns
        -------
        np.array of IWP values

        """
        
        iwp = self.get_data('iwp')
        iwp = np.concatenate(iwp, axis = 0)
        return np.concatenate(iwp)
    
    
    @property
    def wvp(self):
        """
        water vapour path

        Returns
        -------
        np.array of IWP values

        """
        
        wvp = self.get_data('wvp')
        wvp = np.concatenate(wvp, axis = 0)
        return np.concatenate(wvp)
    

    @property
    def lat(self):
        """
        latitudes

        Returns
        -------
        np.array of lat values

        """
        
        lat = self.get_data('lat')
        lat = np.concatenate(lat, axis = 0)
        return np.concatenate(lat)
          
    @property
    def stype(self):
        """
        latitudes

        Returns
        -------
        np.array of lat values

        """
        
        stype = self.get_data('stype')
        stype = np.concatenate(stype, axis = 0)
        return np.concatenate(stype)
          
    
    
    def pdf(self, bins = None, plot = True):
        """
        generates pdf of Tb from IceCube simulations

        These are not antenna weighted,
        Just to make a quick check.
        Parameters
        ----------
        bins : np.array, optional
            intervals over which PDF is to be computed. The default is None.
            When None, default bins used are np.arange(100, 300, 0.5)
        plot : boolean, optional
            if true, generates a plot of the PDF. The default is True.

        Returns
        -------
        hist[0] : np.array, The values of the histogram

        """
        
        tb = self.tb
        

        bins = np.arange(100, 310, 1)
        fig, ax = plt.subplots(1,1, figsize = [8, 8])
        
        for i in range(4):
        
            hist = np.histogram(tb[:, i], bins, density = True)
        
            if plot:
            

                ax.plot(bins[:-1], hist[0], label = i)
                ax.set_yscale('log')
                ax.set_ylabel('PDF [#/K]')
                ax.set_xlabel('TB [K]')
                ax.legend()
        return hist[0]
    



    
